import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import { auth } from "@/src/lib/auth";
import { SessionProvider } from "next-auth/react";
import Footer from "./components/Footer";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   const session = await auth();

   return (
      <html lang="en">
         <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}>
            <SessionProvider>
               <NavBar session={session} />
               {children}
               <Footer />
            </SessionProvider>
         </body>
      </html>
   );
}
